RK2015 source code
* use ECC for Mobile-ID
* use signed voter lists
* ID-card voting protocol with state

diff --git a/ivote-server/debian/evote-common.postinst b/ivote-server/debian/evote-common.postinst
--- a/ivote-server/debian/evote-common.postinst
+++ b/ivote-server/debian/evote-common.postinst
@@ -1,57 +1,94 @@
 #!/bin/sh
+# postinst script for evote-common
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-common
 EVREG_CONFIG=/var/evote/registry
 EVREG_CONFIG_STATE=$EVREG_CONFIG/common/state
 
 case "$1" in
-	configure|abort-upgrade|abort-remove|abort-deconfigure)
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-	;;
+    configure)
+        # create registry directory
+        test -d $EVREG_CONFIG/common || mkdir --parents $EVREG_CONFIG/common
+        chgrp www-data $EVREG_CONFIG $EVREG_CONFIG/common
+        chmod 2770 $EVREG_CONFIG $EVREG_CONFIG/common
+
+        # set registry to setup state
+        if [ ! -f ${EVREG_CONFIG_STATE} ]; then
+            echo -n "integer:1" > $EVREG_CONFIG_STATE
+            chmod g+w $EVREG_CONFIG_STATE
+        fi
+
+        # to enable restore registry
+        chgrp -R www-data /var/evote
+        chmod -R g+w /var/evote
+
+        # reconfigure autofs
+        AUTODIR="/var/autofs/misc"
+        AUTODVD="${AUTODIR}/dvd"
+        echo "# auto.master for evote" > /etc/auto.master
+        echo "# see autofs(5)" >> /etc/auto.master
+        echo "${AUTODIR} /etc/auto.evote --timeout=5" >> /etc/auto.master
+        invoke-rc.d autofs reload
+
+        # link /dvd to automounter
+        DVDROM=/dvd
+        if [ ! -L ${DVDROM} ]; then
+            if [ -d ${DVDROM} ]; then
+                rmdir /dvd
+            fi
+            ln -s ${AUTODVD} /dvd
+        fi
+
+        # allow users to umount dvd
+        if ! egrep --quiet ${AUTODVD} /etc/fstab; then
+            echo >> /etc/fstab
+            echo "/dev/dvd	${AUTODVD}	iso9660	ro,users,noauto	0	0" >> /etc/fstab
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
-# create registry directory
-test -d $EVREG_CONFIG/common || mkdir --parents $EVREG_CONFIG/common
-chgrp www-data $EVREG_CONFIG $EVREG_CONFIG/common
-chmod 2770 $EVREG_CONFIG $EVREG_CONFIG/common
 
-# set registry to setup state
-if [ ! -f ${EVREG_CONFIG_STATE} ]; then
-	echo -n "integer:1" > $EVREG_CONFIG_STATE
-	chmod g+w $EVREG_CONFIG_STATE
-fi
+# compile python files
+case "$1" in
+    configure|abort-upgrade|abort-remove|abort-deconfigure)
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+    ;;
+esac
 
-# to enable restore registry
-chgrp -R www-data /var/evote
-chmod -R g+w /var/evote
 
-# reconfigure autofs
-AUTODIR="/var/autofs/misc"
-AUTODVD="${AUTODIR}/dvd"
-echo "# auto.master for evote" > /etc/auto.master
-echo "# see autofs(5)" >> /etc/auto.master
-echo "${AUTODIR} /etc/auto.evote --timeout=5" >> /etc/auto.master
-invoke-rc.d autofs reload
-
-# link /dvd to automounter
-DVDROM=/dvd
-if [ ! -L ${DVDROM} ]; then
-	if [ -d ${DVDROM} ]; then
-		rmdir /dvd
-	fi
-	ln -s ${AUTODVD} /dvd
-fi
-
-# allow users to umount dvd
-if ! egrep --quiet ${AUTODVD} /etc/fstab; then
-	echo >> /etc/fstab
-	echo "/dev/dvd	${AUTODVD}	iso9660	ro,users,noauto	0	0" >> /etc/fstab
-fi
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hes.postinst b/ivote-server/debian/evote-hes.postinst
--- a/ivote-server/debian/evote-hes.postinst
+++ b/ivote-server/debian/evote-hes.postinst
@@ -1,4 +1,22 @@
 #!/bin/sh
+# postinst script for evote-hes
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 . /usr/share/debconf/confmodule
 
@@ -9,86 +27,115 @@ USER=hes
 
 TYPE_DIR=/var/evote/registry/common/hes
 
-if [ "$1" = configure ] ; then
+case "$1" in
+    configure)
+        test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
 
-	test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
+        invoke-rc.d apache2 stop
+        a2enmod cgid
+        a2enmod ssl
+        a2enmod unique_id
+        a2enmod log_forensic
+        ln -sf /etc/evote/hes-apache.conf /etc/apache2/sites-available/hes-apache
+        a2ensite hes-apache
+        a2dissite default || true
 
-	invoke-rc.d apache2 stop
-	a2enmod cgi
-	a2enmod ssl
-	a2enmod unique_id
-	a2enmod log_forensic
-	ln -sf /etc/evote/hes-apache.conf /etc/apache2/sites-available/hes-apache
-	a2ensite hes-apache
-	a2dissite default || true
+        PORTS_CONF=/etc/apache2/ports.conf
+        if [ -s ${PORTS_CONF} ]; then
+            cp ${PORTS_CONF} ${PORTS_CONF}.bak
+            echo -n > ${PORTS_CONF}
+        fi
 
-	mv /etc/apache2/ports.conf /etc/apache2/ports.conf.old
-	touch /etc/apache2/ports.conf
-
-
-	LOGROTATE="/etc/logrotate.d/apache2"
-	if [ -e $LOGROTATE ] ; then
-		TMP=`tempfile`
-		chmod --reference=$LOGROTATE $TMP
-		cat << EOF > $TMP
+        LOGROTATE="/etc/logrotate.d/apache2"
+        if [ -e $LOGROTATE ] ; then
+            TMP=`tempfile`
+            chmod --reference=$LOGROTATE $TMP
+            cat << EOF > $TMP
 /var/log/apache2/*.log {
-	weekly
-	missingok
-	rotate 52
-	nocompress
-	create 640 root www-data
-	sharedscripts
-	postrotate
-		/etc/init.d/apache2 reload > /dev/null
-	endscript
-	prerotate
-		if [ -d /etc/logrotate.d/httpd-prerotate ]; then \\
-			run-parts /etc/logrotate.d/httpd-prerotate; \\
-		fi; \\
-	endscript
+        weekly
+        missingok
+        rotate 52
+        nocompress
+        create 640 root www-data
+        sharedscripts
+        postrotate
+                /etc/init.d/apache2 reload > /dev/null
+        endscript
+        prerotate
+                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \\
+                        run-parts /etc/logrotate.d/httpd-prerotate; \\
+                fi; \\
+        endscript
 }
 EOF
-		mv $TMP $LOGROTATE
-	fi
+            mv $TMP $LOGROTATE
+        fi
 
-	chgrp www-data /var/log/apache2
-	chmod g+rxs /var/log/apache2
-	touch /var/log/apache2/forensic.log
-	set +e
-	chown root /var/log/apache2/*log*
-	chgrp www-data /var/log/apache2/*log*
-	chmod 640 /var/log/apache2/*log*
-	set -e
+        chgrp www-data /var/log/apache2
+        chmod g+rxs /var/log/apache2
+        touch /var/log/apache2/forensic.log
+        set +e
+        chown root /var/log/apache2/*log*
+        chgrp www-data /var/log/apache2/*log*
+        chmod 640 /var/log/apache2/*log*
+        set -e
 
-	db_get evote-hes/log_server_ip
-	LOGIP="$RET"
-	db_stop
-	SYSLOGCONF="/etc/evote/hes-syslog.conf"
-	TMP=`tempfile`
-	chmod --reference=$SYSLOGCONF $TMP
-	sed -e "s/TOBEREPLACED/$LOGIP/" $SYSLOGCONF > $TMP
-	mv $TMP $SYSLOGCONF
-	ln -sf $SYSLOGCONF /etc/rsyslog.d/hes-syslog.conf
-	invoke-rc.d rsyslog restart
-fi
+        echo
+        if apache2ctl configtest >/dev/null 2>&1; then
+            echo 'Veebiserveri sätted on korras, serveri taaskäivitamine...'
+            service apache2 restart
+        else
+            db_input high evote-hes/apache-config || true
+            db_go
+        fi
 
-case "$1" in
-	configure|abort-upgrade|abort-remove|abort-deconfigure)
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-	;;
+        db_get evote-hes/log_server_ip
+        LOGIP="$RET"
+        db_stop
+        SYSLOGCONF="/etc/evote/hes-syslog.conf"
+        TMP=`tempfile`
+        chmod --reference=$SYSLOGCONF $TMP
+        sed -e "s/TOBEREPLACED/$LOGIP/" $SYSLOGCONF > $TMP
+        mv $TMP $SYSLOGCONF
+        ln -sf $SYSLOGCONF /etc/rsyslog.d/hes-syslog.conf
+        invoke-rc.d rsyslog restart
+
+        # create user
+        GID=`grep ^www-data: /etc/group | cut -d: -f 3`
+        getent passwd $USER >/dev/null 2>&1 ||
+            adduser --quiet --system --home /tmp \
+                    --gid $GID \
+                    --shell /usr/share/evote/evote_ui $USER 
+        adduser --quiet $USER cdrom
+        invoke-rc.d cron restart || true
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
-# create user
-GID=`grep ^www-data: /etc/group | cut -d: -f 3`
-getent passwd $USER >/dev/null 2>&1 ||
-				adduser --quiet --system --home /tmp \
-			--gid $GID \
-			--shell /usr/share/evote/evote_ui $USER 
-adduser --quiet $USER cdrom
-invoke-rc.d cron restart || true
+
+# compile python files
+case "$1" in
+    configure|abort-upgrade|abort-remove|abort-deconfigure)
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hes.postrm b/ivote-server/debian/evote-hes.postrm
--- a/ivote-server/debian/evote-hes.postrm
+++ b/ivote-server/debian/evote-hes.postrm
@@ -1,28 +1,58 @@
 #!/bin/sh
+# postrm script for evote
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-hes
 USER=hes
 
-APA1=/etc/apache2/sites-enabled/hes-apache
-APA2=/etc/apache2/sites-available/hes-apache
+case "$1" in
+    purge)
+        deluser --quiet $USER > /dev/null || true
+    ;;
 
-PORTS_CONF=/etc/apache2/ports.conf.old
-if [ -e $PORTS_CONF ] ; then
-	mv $PORTS_CONF /etc/apache2/ports.conf
-fi
+    remove)
+        PORTS_CONF=/etc/apache2/ports.conf
+        if [ -e ${PORTS_CONF}.bak ]; then
+            mv ${PORTS_CONF}.bak ${PORTS_CONF}
+        fi
 
-if [ "$1" = remove ] ; then
-	if [ -e $APA1 ] ; then rm -f $APA1 ; fi
-	if [ -e $APA2 ] ; then rm -f $APA2 ; fi
-	invoke-rc.d apache2 stop || true
-fi
+        rm -f /etc/apache2/sites-enabled/hes-apache \
+              /etc/apache2/sites-available/hes-apache
+        invoke-rc.d apache2 stop || true
+    ;;
 
-if [ "$1" = purge ] ; then
-	deluser --quiet $USER > /dev/null || true
-fi
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
 
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hes.prerm b/ivote-server/debian/evote-hes.prerm
--- a/ivote-server/debian/evote-hes.prerm
+++ b/ivote-server/debian/evote-hes.prerm
@@ -1,15 +1,49 @@
 #!/bin/sh
+# prerm script for evote
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
 NAME=evote-hes
 
-#rm -f /var/www/evote/favicon.ico
-#rm -f /var/www/evote/safari
+case "$1" in
+    remove|upgrade|deconfigure)
+        #rm -f /var/www/evote/favicon.ico
+        #rm -f /var/www/evote/safari
 
-dpkg --listfiles $NAME |
-	awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
-	xargs rm -f >&2
+        dpkg --listfiles $NAME |
+            awk '$0~/\.py$/ {print $0"c\n" $0"o"}' |
+            xargs rm -f >&2
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hlr.postinst b/ivote-server/debian/evote-hlr.postinst
--- a/ivote-server/debian/evote-hlr.postinst
+++ b/ivote-server/debian/evote-hlr.postinst
@@ -1,35 +1,73 @@
 #!/bin/sh
+# postinst script for evote-hlr
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-hlr
 USER=hlr
 TMPFS=/var/tmp/evote
 TYPE_DIR=/var/evote/registry/common/hlr
 
-test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
-
 case "$1" in
-	configure|abort-upgrade|abort-remove|abort-deconfigure)
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-	;;
+    configure)
+        test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
+
+        # create user
+        GID=`grep ^www-data: /etc/group | cut -d: -f 3`
+        getent passwd $USER >/dev/null 2>&1 ||
+            adduser --quiet --system --home /tmp \
+                    --gid $GID \
+                    --shell /usr/share/evote/evote_ui $USER 
+        adduser --quiet $USER cdrom
+
+        # tmpfs
+        if ! grep --quiet $TMPFS /etc/fstab; then
+            echo "none		${TMPFS}	tmpfs	defaults		0	0" >> /etc/fstab
+            mount $TMPFS
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
-# create user
-GID=`grep ^www-data: /etc/group | cut -d: -f 3`
-getent passwd $USER >/dev/null 2>&1 ||
-                adduser --quiet --system --home /tmp \
-			--gid $GID \
-			--shell /usr/share/evote/evote_ui $USER 
-adduser --quiet $USER cdrom
 
-# tmpfs
-if ! grep --quiet $TMPFS /etc/fstab; then
-	echo "none		${TMPFS}	tmpfs	defaults		0	0" >> /etc/fstab
-	mount $TMPFS
-fi
+# compile python files
+case "$1" in
+    configure|abort-upgrade|abort-remove|abort-deconfigure)
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hlr.postrm b/ivote-server/debian/evote-hlr.postrm
--- a/ivote-server/debian/evote-hlr.postrm
+++ b/ivote-server/debian/evote-hlr.postrm
@@ -1,13 +1,44 @@
 #!/bin/sh
+# postrm script for evote
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-hlr
 USER=hlr
 
-if [ "$1" = purge ] ; then
-	deluser --quiet $USER > /dev/null || true
-fi
+case "$1" in
+    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+        deluser --quiet $USER > /dev/null || true
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hts.postinst b/ivote-server/debian/evote-hts.postinst
--- a/ivote-server/debian/evote-hts.postinst
+++ b/ivote-server/debian/evote-hts.postinst
@@ -1,96 +1,130 @@
 #!/bin/sh
-
-. /usr/share/debconf/confmodule
+# postinst script for evote-hts
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-hts
 USER=hts
 TYPE_DIR=/var/evote/registry/common/hts
 
-if [ "$1" = configure ] ; then
-
-	test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
-
-	a2enmod cgi
-	a2enmod unique_id
-	a2enmod log_forensic
-	ln -sf /etc/evote/hts-apache.conf /etc/apache2/sites-available/hts-apache
-	a2ensite hts-apache
-	a2dissite default || true
-
-	LOGROTATE="/etc/logrotate.d/apache2"
-	if [ -e $LOGROTATE ] ; then
-		TMP=`tempfile`
-		chmod --reference=$LOGROTATE $TMP
-		cat << EOF > $TMP
-/var/log/apache2/*.log {
-	weekly
-	missingok
-	rotate 52
-	nocompress
-	create 640 root www-data
-	sharedscripts
-	postrotate
-		/etc/init.d/apache2 reload > /dev/null
-	endscript
-	prerotate
-		if [ -d /etc/logrotate.d/httpd-prerotate ]; then \\
-			run-parts /etc/logrotate.d/httpd-prerotate; \\
-		fi; \\
-	endscript
-}
-EOF
-		mv $TMP $LOGROTATE
-	fi
-
-	chgrp www-data /var/log/apache2
-	chmod g+rxs /var/log/apache2
-	touch /var/log/apache2/forensic.log
-	set +e
-	chown root /var/log/apache2/*log*
-	chgrp www-data /var/log/apache2/*log*
-	chmod 640 /var/log/apache2/*log*
-	set -e
-
-	invoke-rc.d apache2 restart
-
-	db_get evote-hts/log_server_ip
-	LOGIP="$RET"
-	db_stop
-	SYSLOGCONF="/etc/evote/hts-syslog.conf"
-	TMP=`tempfile`
-	chmod --reference=$SYSLOGCONF $TMP
-	sed -e "s/TOBEREPLACED/$LOGIP/" $SYSLOGCONF > $TMP
-	mv $TMP $SYSLOGCONF
-	ln -sf $SYSLOGCONF /etc/rsyslog.d/hts-syslog.conf
-	invoke-rc.d rsyslog restart
-fi
+. /usr/share/debconf/confmodule
 
 case "$1" in
-	configure|abort-upgrade|abort-remove|abort-deconfigure)
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-		dpkg --listfiles $NAME | grep '\.py$' | \
-			xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
-	;;
+    configure)
+        test -d $TYPE_DIR || mkdir --parents $TYPE_DIR
+
+        a2enmod cgi
+        a2enmod unique_id
+        a2enmod log_forensic
+        ln -sf /etc/evote/hts-apache.conf /etc/apache2/sites-available/hts-apache
+        a2ensite hts-apache
+        a2dissite default || true
+
+        LOGROTATE="/etc/logrotate.d/apache2"
+        if [ -e $LOGROTATE ] ; then
+            TMP=`tempfile`
+            chmod --reference=$LOGROTATE $TMP
+            cat << EOF > $TMP
+/var/log/apache2/*.log {
+        weekly
+        missingok
+        rotate 52
+        nocompress
+        create 640 root www-data
+        sharedscripts
+        postrotate
+                /etc/init.d/apache2 reload > /dev/null
+        endscript
+        prerotate
+                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \\
+                        run-parts /etc/logrotate.d/httpd-prerotate; \\
+                fi; \\
+        endscript
+}
+EOF
+            mv $TMP $LOGROTATE
+        fi
+
+        chgrp www-data /var/log/apache2
+        chmod g+rxs /var/log/apache2
+        touch /var/log/apache2/forensic.log
+        set +e
+        chown root /var/log/apache2/*log*
+        chgrp www-data /var/log/apache2/*log*
+        chmod 640 /var/log/apache2/*log*
+        set -e
+
+        invoke-rc.d apache2 restart
+
+        db_get evote-hts/log_server_ip
+        LOGIP="$RET"
+        db_stop
+        SYSLOGCONF="/etc/evote/hts-syslog.conf"
+        TMP=`tempfile`
+        chmod --reference=$SYSLOGCONF $TMP
+        sed -e "s/TOBEREPLACED/$LOGIP/" $SYSLOGCONF > $TMP
+        mv $TMP $SYSLOGCONF
+        ln -sf $SYSLOGCONF /etc/rsyslog.d/hts-syslog.conf
+        invoke-rc.d rsyslog restart
+
+        # set max votes per voter
+        EVREG_CONFIG_MAX_VOTES_PER_VOTER=/var/evote/registry/common/max_votes_per_voter
+        if [ ! -f ${EVREG_CONFIG_MAX_VOTES_PER_VOTER} ]; then
+            echo -n "integer:1000" > $EVREG_CONFIG_MAX_VOTES_PER_VOTER
+            chmod g+w $EVREG_CONFIG_MAX_VOTES_PER_VOTER
+        fi
+
+        # create user
+        GID=`grep ^www-data: /etc/group | cut -d: -f 3`
+        getent passwd $USER >/dev/null 2>&1 ||
+            adduser --quiet --system --home /tmp \
+                    --gid $GID \
+                    --shell /usr/share/evote/evote_ui $USER 
+        adduser --quiet $USER cdrom
+        invoke-rc.d cron restart || true
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
 
-# set max votes per voter
-EVREG_CONFIG_MAX_VOTES_PER_VOTER=/var/evote/registry/common/max_votes_per_voter
-if [ ! -f ${EVREG_CONFIG_MAX_VOTES_PER_VOTER} ]; then
-	echo -n "integer:1000" > $EVREG_CONFIG_MAX_VOTES_PER_VOTER
-	chmod g+w $EVREG_CONFIG_MAX_VOTES_PER_VOTER
-fi
 
-# create user
-GID=`grep ^www-data: /etc/group | cut -d: -f 3`
-getent passwd $USER >/dev/null 2>&1 ||
-				adduser --quiet --system --home /tmp \
-			--gid $GID \
-			--shell /usr/share/evote/evote_ui $USER 
-adduser --quiet $USER cdrom
-invoke-rc.d cron restart || true
+# compile python files
+case "$1" in
+    configure|abort-upgrade|abort-remove|abort-deconfigure)
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+        dpkg --listfiles $NAME | grep '\.py$' | \
+            xargs -n 1 /usr/bin/python2.7 -O -c 'import py_compile,sys;py_compile.compile(sys.argv[1])'
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
diff --git a/ivote-server/debian/evote-hts.postrm b/ivote-server/debian/evote-hts.postrm
--- a/ivote-server/debian/evote-hts.postrm
+++ b/ivote-server/debian/evote-hts.postrm
@@ -1,20 +1,53 @@
 #!/bin/sh
+# postrm script for evote
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 NAME=evote-hts
 USER=hts
 
-if [ "$1" = remove ] ; then
-	rm -f /etc/apache2/sites-enabled/hts-apache
-	rm -f /etc/apache2/sites-available/hts-apache
-	invoke-rc.d apache2 restart || true
-fi
+case "$1" in
+    purge)
+        deluser --quiet $USER > /dev/null || true
+    ;;
 
-if [ "$1" = purge ] ; then
-	deluser --quiet $USER > /dev/null || true
-fi
+    remove)
+        rm -f /etc/apache2/sites-enabled/hts-apache \
+              /etc/apache2/sites-available/hts-apache
+        invoke-rc.d apache2 restart || true
+    ;;
 
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
+exit 0
+
+# vim:sts=4 sw=4 et:
